version: 2

build:
   os: "ubuntu-22.04"
   tools:
      python: "3.10"
   commands:
      #
      # xrst
      - pip3 install xrst
      #
      # This is only necessary if you need the most recent testing verison
      - pip3 uninstall -y xrst
      - pip3 install --index-url https://test.pypi.org/simple/ xrst --user
      - PATH="$PATH:$HOME/.local/bin"
      #
      # build/html
      # The xsrst html_directory for this configuration is build/html.
      - xrst
         --page_source
         --html_theme furo
         --group_list default
         --index_page_name at_cascade
      #
      # _readthedocs/html
      # The directory that Read the Docs uploads when commands is used.
      - mkdir _readthedocs
      - rm -r build/html/.doctrees
      - cp -r build/html _readthedocs/html
